# baseURL = 'https://example.org/'
languageCode = 'zh-hans'
title = "Liginity's Blog"
theme = 'PaperMod'
defaultContentLanguage = 'zh'

[params]
  mainSections = ['posts']

[menus]
  [[menus.main]]
    name = '首页'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = '归档'
    pageRef = '/archives'
    weight = 20
  [[menus.main]]
    name = '分类'
    pageRef = '/categories'
    weight = 30
  [[menus.main]]
    name = '简记'
    pageRef = '/short-notes'
    weight = 40

[markup]
  [markup.highlight]
    lineNos = true
    style = 'friendly' # looks like wikipedia color style
    noClasses = false

[permalinks]
  [permalinks.page]
    # NOTE use slugorcontentbasename after hugo v0.144.0.
    posts = '/posts/:year/:slugorfilename/'
