baseURL = 'https://example.org/'
languageCode = 'zh-hans'
title = "Liginity's Blog"
theme = 'PaperMod'
defaultContentLanguage = 'zh'

[markup]
  [markup.highlight]
    lineNos = true
    style = 'friendly' # looks like wikipedia color style

[permalinks]
  [permalinks.page]
    # NOTE use slugorcontentbasename after hugo v0.144.0.
    posts = '/posts/:year/:slugorfilename/'
